news:
  - name: Newsroom
    client: html
    endpoint: https://www.census.gov/newsroom.html
  - name: America Counts
    client: html
    endpoint: https://www.census.gov/library/stories.html
  - name: Stats for Stories
    client: html
    endpoint: https://www.census.gov/newsroom/stories.html
  - name: Economic Indicators
    client: rss
    endpoint: https://www.census.gov/economic-indicators/indicator.xml
  - name: News Releases Only
    client: rss
    endpoint: https://www.census.gov/content/census/en/newsroom/press-releases.xml
  - name: News (All News Items)
    client: rss
    endpoint: https://www.census.gov/newsroom/press-releases/by-year.xml
blogs: 
  - name: Census Blogs
    client: html
    endpoint: https://www.census.gov/newsroom/blogs.html
  - name: Director's Blog
    client: rss
    endpoint: https://www.census.gov/content/census/en/newsroom/blogs/director.xml
  - name: Global Reach Blog
    client: rss
    endpoint: https://www.census.gov/content/census/en/newsroom/blogs/global-reach.xml
  - name: Random Samplings
    client: rss
    endpoint: https://www.census.gov/content/census/en/newsroom/blogs/random-samplings.xml
  - name: Research Matters
    client: rss
    endpoint: https://www.census.gov/content/census/en/newsroom/blogs/research-matters.xml