 catalogs:
  - name: Open Datasets Portal
    platform: ckan
    client: html
    endpoint: https://data.gov.ro/
    lang: ro
  - name: Open Datasets Portal
    platform: ckan
    client: rest
    endpoint: https://data.gov.ro/api
    lang: ro   