title: Agency Registry
#base_url: http://127.0.0.1:4000

version:      1.1.1
author:
  name:       'Kin Lane'
  email:      'info@apievangelist.com'
markdown:     kramdown

permalink: /:categories/:year/:month/:day/:title/
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md", ".DS_Store", "omad", "utils", "schemas"]

github_user: integrateddatasvc
github_repo: agency-registry

collections:
  registry:
    output: true
    permalink: /registry/:path/
  data:
    output: true
    permalink: /data/:path/

defaults:
  - scope:
      type: registry
    values:
      layout: registry
  - scope:
      type: data
    values:
      layout: data
