title: Agency Registry

version:      1.1.1
author:
  name:       'Kin Lane'
  email:      'info@apievangelist.com'
markdown:     kramdown

permalink: /:categories/:year/:month/:day/:title/
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md", ".DS_Store", "omad", "utils", "schemas"]

github_user: integrateddatasvc
github_repo: agency-registry

theme: jekyll-theme-minimal