catalogs:
  - name: Publications & Products
    client: html
    endpoint: https://nces.ed.gov/pubsearch/
    lang: en
  - name: Annual Reports
    client: html
    endpoint: https://nces.ed.gov/surveys/annualreports/
    lang: en
  - name: Online Analysis
    client: html
    endpoint: https://nces.ed.gov/datatools/index.asp?DataToolSectionID=2
    lang: en
calendars: 
  - name: What's New
    client: html
    endpoint: https://nces.ed.gov/whatsnew/
    lang: en
news:
  - name: What's New
    client: rss
    endpoint: http://nces.ed.gov/whatsnew/whatsnew_rss.asp
    lang: en
  - name: Recent Publications
    client: rss
    endpoint: http://nces.ed.gov/pubSearch/pubs_rss.asp
    lang: en