news:
  - name: Publications
    client: html
    endpoint: https://www.ers.usda.gov/publications/
    lang: en
  - name: Newsroom
    client: html
    endpoint: https://www.ers.usda.gov/newsroom/
    lang: en
catalogs:
  - name: Data Products
    client: html
    endpoint: https://www.ers.usda.gov/data-products/
    lang: en
calendars:
  - name: Calendar
    client: html
    endpoint: https://www.ers.usda.gov/calendar/
    lang: en