catalogs:
  - name: CMS Data
    client: html
    endpoint: https://data.cms.gov/
    lang: en
  - name: Medicare provider data
    client: html
    endpoint: https://data.cms.gov/provider-data/
    lang: en
  - name: CMS Data (beta)
    client: html
    endpoint: https://data.cms.gov/beta/
    lang: en


  

