sites:
  - name: Canada Open Data
    client: html
    endpoint: https://open.canada.ca/en/open-data
    lang: en
  - name: Données ouvertes du Canada
    client: html
    endpoint: https://ouvert.canada.ca/fr/donnees-ouvertes
    lang: en
catalogs:
  - name: Open Government Portal
    client: html
    endpoint: https://search.open.canada.ca/en/od/
    lang: en
  - name: Portail du gouvernement ouvert
    client: html
    endpoint: https://rechercher.ouvert.canada.ca/fr/od/
    lang: fr