blogs:
  - name: Global Reach Blog
    description: Get foreign trade data reports, information on Trade Regulations and answers to your questions from the official source of US Import & Export Trade Statistics.
    client: atom
    endpoint: https://www.census.gov/content/census/en/newsroom/blogs/global-reach.xml
  - name: Random Sampling
    description: Experts from the Census Bureau describe the objectives of their work and explain census and survey results. The bureau conducts more than 100 surveys each year.
    client: atom
    endpoint: https://www.census.gov/content/census/en/newsroom/blogs/random-samplings.xml
  - name: Research Matters
    description: Scientists from the Census Bureau describe the importance of research in survey design, methodology, modeling, record linkage, confidentiality protection, etc.
    client: atom
    endpoint: https://www.census.gov/content/census/en/newsroom/blogs/research-matters.xml
catalogs:
  - name: U.S. Census data catalog
    client: html
    endpoint: https://www.census.gov/data.html
    lang: en
news:
  - name: Economic Indicators
    description: Key National Economic Indicators Published by the U.S. Census Bureau
    client: atom
    endpoint: https://www.census.gov/economic-indicators/indicator.xml
    lang: en
