news:
  - name: Press Releases
    client: html
    endpoint: https://www.usagm.gov/news-and-information/press-releases/
  - name: Events
    client: html
    endpoint: https://www.usagm.gov/news-and-information/events/
  - name: Threats To Press
    client: html
    endpoint: https://www.usagm.gov/news-and-information/threats-to-press/
  - name: Press Room
    client: html
    endpoint: https://www.usagm.gov/news-and-information/press-room/
  - name: Press Room
    client: rss
    endpoint: https://www.usagm.gov/category/press-release/feed/
  - name: Research Reports
    client: html
    endpoint: https://www.usagm.gov/our-work/strategy-and-results/strategic-priorities/research-reports/