news:
  - name: SOI Tax Stats - What's New
    client: html
    endpoint: https://www.irs.gov/statistics/soi-tax-stats-whats-new
    lang: en
calendars:
  - name: SOI Tax Stats - Upcoming Data Releases
    client: html
    endpoint: https://www.irs.gov/statistics/soi-tax-stats-upcoming-data-releases
    lang: en
catalogs:
  - name: SOI Tax Stats - Products, Publications, and Papers
    client: html
    endpoint: https://www.irs.gov/statistics/soi-tax-stats-products-publications-and-papers
    lang: en
  - name: SOI Tax Stats - IRS Data Book
    client: html
    endpoint: https://www.irs.gov/statistics/soi-tax-stats-irs-data-book
    lang: en
  - name: SOI Tax Stats - Buisness Tax Satistics
    client: html
    endpoint: https://www.irs.gov/statistics/soi-tax-stats-business-tax-statistics
    lang: en
  - name: SOI Tax Stats - Individual Tax Satistics
    client: html
    endpoint: https://www.irs.gov/statistics/soi-tax-stats-individual-tax-statistics
    lang: en
  - name: IRS - Other IRS Data and Research
    client: html
    endpoint: https://www.irs.gov/statistics/irs-other-irs-data-and-research
    lang: en