news:
  - name: What's New
    client: html
    endpoint: https://www.eia.gov/about/new/
    lang: en
  - name: Press Room
    client: html
    endpoint: https://www.eia.gov/pressroom/
    lang: en
  - name: Gasoline & Diesel Fuel Update
    client: rss
    endpoint: https://www.eia.gov/petroleum/gasdiesel/includes/gas_diesel_rss.xml
    lang: en
  - name: Press Releases
    client: rss
    endpoint: https://www.eia.gov/rss/press_rss.xml
    lang: en
  - name: Heating Oil and Propane Update
    client: rss
    endpoint: https://www.eia.gov/petroleum/heatingoilpropane/includes/hopu_rss.xml
    lang: en
calendars: 
  - name: All Reports & Publications
    client: html
    endpoint: https://www.eia.gov/reports/upcoming.php
    lang: en
catalogs: 
  - name: All Reports & Publications
    client: html
    endpoint: https://www.eia.gov/reports/
    lang: en