catalogs:
  - name: Datenportal für Deutschland
    platform: ckan
    client: html
    endpoint: https://www.govdata.de/
    api_endpoint: https://www.govdata.de/ckan/catalog/catalog.rdf
    lang: de