news:
  - name: COVID-19 Vaccination Data Updates
    client: rss
    endpoint: https://tools.cdc.gov/api/v2/resources/media/415826.rss
  - name: Food Safety
    client: rss
    endpoint: https://tools.cdc.gov/api/v2/resources/media/316422.rss
  - name: Preventing Chronic Disease
    client: rss
    endpoint: https://tools.cdc.gov/api/v2/resources/media/322083.rss
  - name: CDC Cancer Research
    client: rss
    endpoint: https://tools.cdc.gov/api/v2/resources/media/316303.rss
  - name: CDC Travel Noctices
    client: rss
    endpoint: https://tools.cdc.gov/api/v2/resources/media/285740.rss
  - name: CDC Cancer News
    client: rss
    endpoint: https://tools.cdc.gov/api/v2/resources/media/316302.rss
  - name: COVID-19
    client: rss
    endpoint: https://tools.cdc.gov/api/v2/resources/media/322085.rss
  - name: CDC Cancer Features
    client: rss
    endpoint: https://tools.cdc.gov/api/v2/resources/media/322085.rss
  - name: 2019 Novel Coronavirus
    client: rss
    endpoint: https://tools.cdc.gov/api/v2/resources/media/403372.rss
  - name: Seasonal Flu
    client: rss
    endpoint: https://tools.cdc.gov/api/v2/resources/media/277692.rss
  - name: CDC Online Newsroom
    client: rss
    endpoint: https://tools.cdc.gov/api/v2/resources/media/132608.rss
  - name: CDC  Outbreaks - US Based
    client: rss
    endpoint: https://tools.cdc.gov/api/v2/resources/media/285676.rss
  - name: Injection Safety
    client: rss
    endpoint: https://tools.cdc.gov/api/v2/resources/media/342777.rss
  - name: Healthy Living Features
    client: rss
    endpoint: https://tools.cdc.gov/api/v2/resources/media/132036.rss
  - name: COVID-19 Vaccine Information for Healthcare Professionals & Health Departments
    client: rss
    endpoint: https://tools.cdc.gov/api/v2/resources/media/415011.rss
  - name: Morbidity and Mortality Weekly Report (MMWR)
    client: rss
    endpoint: https://tools.cdc.gov/api/v2/resources/media/342778.rss
  - name: COVID-19 Science Updates Feed
    client: rss
    endpoint: https://tools.cdc.gov/api/v2/resources/media/410930.rss
  - name: HAN Managed Feed
    client: rss
    endpoint: https://tools.cdc.gov/api/v2/resources/media/413690.rss
  - name: FluView Weekly Summary
    client: rss
    endpoint: https://tools.cdc.gov/api/v2/resources/media/132565.rss
  - name: MMWR (Journal)
    client: rss
    endpoint: https://tools.cdc.gov/api/v2/resources/media/132599.rss
  - name: Faststats
    client: rss
    endpoint: https://tools.cdc.gov/api/v2/resources/media/132512.rss
  - name: 2020-LOCS-Message-Feed
    client: rss
    endpoint: https://tools.cdc.gov/api/v2/resources/media/408831.rss
  - name: 2018 Eastern DRC Ebola Outbreak (ongoing)
    client: rss
    endpoint: https://tools.cdc.gov/api/v2/resources/media/401066.rss
  - name: Vital Signs Website
    client: rss
    endpoint: https://tools.cdc.gov/api/v2/resources/media/275866.rss
  - name: Outbreaks
    client: rss
    endpoint: https://tools.cdc.gov/api/v2/resources/media/281321.rss
  - name: Health Alert Network (HAN)
    client: rss
    endpoint: https://tools.cdc.gov/api/v2/resources/media/320567.rss
  - name: Diabetes RSS Feed
    client: rss
    endpoint: https://tools.cdc.gov/api/v2/resources/media/350460.rss
  - name: HIV
    client: rss
    endpoint: https://tools.cdc.gov/api/v2/resources/media/342776.rss
  - name: Latest Funding Opportunities for American Indian and Alaska Native Communities
    client: rss
    endpoint: https://tools.cdc.gov/api/v2/resources/media/319131.rss
  - name: TWH News
    client: rss
    endpoint: https://tools.cdc.gov/api/v2/resources/media/382852.rss
  - name: Zika - What's New
    client: rss
    endpoint: https://tools.cdc.gov/api/v2/resources/media/279735.rss
  - name: Public Health Professionals Gateway
    client: rss
    endpoint: https://tools.cdc.gov/api/v2/resources/media/317000.rss
  - name: CDC Outbreaks - Affecting International Travelers
    client: rss
    endpoint: https://tools.cdc.gov/api/v2/resources/media/132782.rss
  - name: "CDC Listeria: Outbreak Updates"
    client: rss
    endpoint: https://tools.cdc.gov/api/v2/resources/media/321471.rss
  - name: "CDC Salmonella: Outbreak Updates"
    client: rss
    endpoint: https://tools.cdc.gov/api/v2/resources/media/342774.rss
  - name: "CDC E. coli: Outbreak Updates"
    client: rss
    endpoint: https://tools.cdc.gov/api/v2/resources/media/342773.rss
  - name: Safe Healthcare
    client: rss
    endpoint: https://tools.cdc.gov/api/v2/resources/media/320640.rss
  - name: Kids' Health RSS
    client: rss
    endpoint: https://tools.cdc.gov/api/v2/resources/media/316737.rss
  - name: Women's Health RSS
    client: rss
    endpoint: https://tools.cdc.gov/api/v2/resources/media/316543.rss
  - name: NCHS Publications & Products
    client: rss
    endpoint: https://tools.cdc.gov/api/v2/resources/media/319817.rss
  - name: MMWR QuickStats
    client: rss
    endpoint: https://tools.cdc.gov/api/v2/resources/media/320959.rss
  - name: CDC Clinician Outreach and Communication Activity (COCA)
    client: rss
    endpoint: https://tools.cdc.gov/api/v2/resources/media/320671.rss
  - name: CDC Around the World
    client: rss
    endpoint: https://tools.cdc.gov/api/v2/resources/media/132482.rss
  - name: "CDC C. auris: What's New"
    client: rss
    endpoint: https://tools.cdc.gov/api/v2/resources/media/355815.rss