news:
  - name: 2021 TransBorder Data Port and Commodity
    client: rss
    endpoint: https://data.bts.gov/api/views/uxue-t623/rows.rss?accessType=DOWNLOAD
  - name: Border Crossing Entry Data
    client: rss
    endpoint: https://data.bts.gov/api/views/keg4-3bc2/rows.rss?accessType=DOWNLOAD
  - name: Trips by Distance
    client: rss
    endpoint: https://data.bts.gov/api/views/w96p-f2qv/rows.rss?accessType=DOWNLOAD
  - name: News and Statistical Releases
    client: html
    endpoint: https://www.bts.gov/statistical-releases
calendars:
  - name: Upcoming Statistical Releases and Webinars
    client: html
    endpoint: https://www.bts.gov/events