calendars:
  - name: Forthcoming Publications & Products
    client: html
    endpoint: https://www.bjs.gov/index.cfm?ty=fcp
    lang: en
catalogs: 
  - name: All Data Collections
    client: html
    endpoint: https://www.bjs.gov/index.cfm?ty=dca
    lang: en